######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 17 10:46:33 2009
######################################################################
include(../../config.pri)

TEMPLATE = app
TARGET = 
DEPENDPATH += ../../$$NTTW_INCLUDEPATH
INCLUDEPATH += ../../$$NTTW_INCLUDEPATH
DESTDIR = ../../bin
OBJECTS_DIR += ../../obj

CONFIG += qt warn_on release console
QT -= gui #Use only core module
unix:DEFINES += QT_SHARED
DEFINES += QT_DLL NTTW_DLL

unix:LIBS += -L../../$$NTTW_LIBSPATH $$NTTW_LIBS -lrt
win32-msvc2005:LIBS += /LIBPATH:"../../$$NTTW_LIBSPATH" $$NTTW_LIBS
win32-g++:LIBS += -L../../$$NTTW_LIBSPATH $$NTTW_LIBS -lrt

# Input
SOURCES += timing_test.c
